apiVersion: v1
kind: ConfigMap
metadata:
  name: servicebus-ingester-dotnet-config
  namespace: experiment
data:
  CONSUMER_COUNT: "20"
  BATCH_SIZE: "100"
  HEALTH_PORT: "8080"
  SERVICEBUS_TOPIC: "sb-loadtest-listen"
  SERVICEBUS_SUBSCRIPTION: "servicebus-ingester-dotnet"
  DB_USER: "ingestionservicebusingesterdotnet"
  DB_PORT: "5432"
  DB_DATABASE: "vce_experiment_ingestion_servicebusingesterdotnet"
  DB_SCHEMA: "ingestionservicebusingesterdotnet"
  DB_SSL_MODE: "require"
  DB_MAX_CONNS: "20"
  DB_CONNECTION_IDLE_TIME_MINUTES: "5"
  DB_CONNECTION_LIFE_TIME_MINUTES: "30"
  SERVICEBUS_SEND_TOPIC: "sb-loadtest-send"
