apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: servicebus-ingester-dotnet-kv-experiment-config
  namespace: experiment
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kv-vce-experiment-dev
    kind: SecretStore
  target:
    name: servicebus-ingester-dotnet-kv-experiment-config
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB-ingestion-servicebus-ingester
    - secretKey: DB_HOST
      remoteRef:
        key: DB-host
    - secretKey: SB_CONNECTION_STRING
      remoteRef:
        key: SB-ConnectionString
